import type { ThemeConfig } from 'antd';

const sansStack =
  '"Inter Variable", "Inter", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", helvetica, Arial, sans-serif';

export const appleTheme: ThemeConfig = {
  token: {
    colorPrimary: '#5e6ad2',
    colorLink: '#7170ff',
    colorLinkHover: '#828fff',
    colorSuccess: '#10b981',
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#7170ff',
    colorText: '#08090a',
    colorTextSecondary: '#3c4149',
    colorTextTertiary: '#6b7280',
    colorTextQuaternary: '#9ca3af',
    colorTextLightSolid: '#ffffff',
    colorBgBase: '#ffffff',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#ffffff',
    colorBgSpotlight: '#f7f8f8',
    colorBorder: '#e6e6e6',
    colorBorderSecondary: 'rgba(0, 0, 0, 0.05)',
    colorFill: 'rgba(0, 0, 0, 0.04)',
    colorFillSecondary: 'rgba(0, 0, 0, 0.02)',
    colorFillTertiary: 'rgba(0, 0, 0, 0.02)',
    colorFillQuaternary: 'rgba(0, 0, 0, 0.02)',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    borderRadiusXS: 2,
    fontFamily: sansStack,
    fontSize: 14,
    lineHeight: 1.5,
    boxShadow: 'rgba(0, 0, 0, 0.06) 0px 0px 0px 1px',
    boxShadowSecondary: 'rgba(0, 0, 0, 0.08) 0px 2px 4px',
    boxShadowTertiary: 'rgba(0, 0, 0, 0.03) 0px 1.2px 0px 0px',
    controlOutline: 'rgba(113, 112, 255, 0.15)',
    controlOutlineWidth: 3,
    wireframe: false,
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      bodyBg: '#ffffff',
      triggerBg: '#ffffff',
    },
    Button: {
      borderRadius: 6,
      borderRadiusLG: 6,
      borderRadiusSM: 6,
      controlHeight: 36,
      controlHeightSM: 28,
      primaryShadow: 'none',
      defaultShadow: 'none',
      contentFontSize: 14,
      fontWeight: 510,
      defaultBg: '#ffffff',
      defaultColor: '#08090a',
      defaultBorderColor: '#e6e6e6',
      primaryColor: '#ffffff',
      colorPrimary: '#5e6ad2',
      colorPrimaryHover: '#828fff',
      colorPrimaryActive: '#5e6ad2',
    },
    Card: {
      borderRadiusLG: 8,
      headerFontSize: 16,
      headerFontSizeSM: 14,
      colorBgContainer: '#ffffff',
    },
    Input: {
      activeBorderColor: '#7170ff',
      hoverBorderColor: '#d0d6e0',
      activeShadow: '0 0 0 3px rgba(113, 112, 255, 0.15)',
      controlHeight: 40,
      borderRadius: 6,
      borderRadiusLG: 6,
      borderRadiusSM: 4,
      colorBgContainer: '#ffffff',
      colorTextPlaceholder: '#9ca3af',
    },
    InputNumber: {
      activeBorderColor: '#7170ff',
      hoverBorderColor: '#d0d6e0',
      activeShadow: '0 0 0 3px rgba(113, 112, 255, 0.15)',
      borderRadius: 6,
    },
    Select: {
      activeBorderColor: '#7170ff',
      hoverBorderColor: '#d0d6e0',
      controlHeight: 40,
      optionSelectedBg: 'rgba(113, 112, 255, 0.1)',
      optionActiveBg: 'rgba(0, 0, 0, 0.04)',
      borderRadius: 6,
      colorBgContainer: '#ffffff',
    },
    Tabs: {
      itemColor: '#6b7280',
      itemHoverColor: '#08090a',
      itemSelectedColor: '#08090a',
      inkBarColor: '#7170ff',
      titleFontSize: 14,
    },
    Table: {
      headerBg: 'transparent',
      rowHoverBg: 'rgba(0, 0, 0, 0.04)',
      headerColor: '#6b7280',
      borderColor: 'rgba(0, 0, 0, 0.05)',
      colorBgContainer: 'transparent',
    },
    Modal: {
      contentBg: '#ffffff',
      headerBg: '#ffffff',
      footerBg: '#ffffff',
      titleColor: '#08090a',
      titleFontSize: 18,
      borderRadiusLG: 12,
    },
    Drawer: {
      colorBgElevated: '#ffffff',
    },
    Popover: {
      colorBgElevated: '#ffffff',
    },
    Notification: {
      colorBgElevated: '#ffffff',
    },
    Breadcrumb: {
      linkColor: '#6b7280',
      itemColor: '#6b7280',
      lastItemColor: '#08090a',
      separatorColor: '#9ca3af',
    },
    Typography: {
      titleMarginBottom: '0.5em',
      titleMarginTop: 0,
      colorLink: '#7170ff',
      colorLinkHover: '#828fff',
    },
    Tag: {
      borderRadiusSM: 9999,
      colorBorder: '#e6e6e6',
    },
    Timeline: {
      dotBorderWidth: 2,
      tailColor: 'rgba(0, 0, 0, 0.08)',
    },
    List: {
      colorBorder: 'rgba(0, 0, 0, 0.05)',
    },
    Empty: {
      colorTextDisabled: '#9ca3af',
    },
    Spin: {
      colorPrimary: '#7170ff',
    },
    Alert: {
      borderRadiusLG: 8,
    },
    Form: {
      labelColor: '#3c4149',
      labelFontSize: 13,
    },
    Checkbox: {
      colorPrimary: '#5e6ad2',
      colorPrimaryHover: '#828fff',
    },
    Radio: {
      colorPrimary: '#5e6ad2',
    },
    Switch: {
      colorPrimary: '#5e6ad2',
    },
  },
};
